import type { Agent, AgentFileKind, HandoffTarget, Memory, Project, PromptSession, Secret, Skill } from "./types.js";
import { agentsMarkdown, memoriesMarkdown, projectContext, secretsMarkdown, skillsMarkdown } from "./project.js";

export function getAgentFileName(kind: AgentFileKind) {
  switch (kind) {
    case "agents":
      return "AGENTS.md";
    case "claude":
      return "CLAUDE.md";
    case "cursor":
      return ".cursor/rules/project.md";
    case "openclaw":
      return "OPENCLAW.md";
  }
}

export function getAgentFileType(kind: AgentFileKind) {
  switch (kind) {
    case "agents":
      return "AGENTS.md";
    case "claude":
      return "CLAUDE.md";
    case "cursor":
      return "Cursor Rules";
    case "openclaw":
      return "OPENCLAW.md";
  }
}

export function generateAgentFile({
  agents,
  kind,
  memories,
  project,
  secrets,
  skills
}: {
  agents: Agent[];
  kind: AgentFileKind;
  memories: Memory[];
  project: Project;
  secrets: Secret[];
  skills: Skill[];
}) {
  const title = getAgentFileType(kind);

  return `# ${title}

This file was generated by AgentDock CLI. It contains portable project context for AI coding agents.

${projectContext(project)}

${agentsMarkdown(agents)}

${memoriesMarkdown(memories)}

${skillsMarkdown(skills)}

${secretsMarkdown(secrets)}

## Agent Rules
- Read project context before editing.
- Use memories and skills as guidance.
- Treat secrets as references only; never request or print raw values.
- Keep changes focused and explain validation commands.
`;
}

export function generatePrompt({
  agent,
  memories,
  project,
  secrets,
  skills,
  task
}: {
  agent: Agent;
  memories: Memory[];
  project: Project;
  secrets: Secret[];
  skills: Skill[];
  task: string;
}) {
  const allowedMemories = getAgentMemories(agent, memories);
  const allowedSkills = getAgentSkills(agent, skills);
  const allowedSecrets = getAgentSecrets(agent, secrets);

  return `# AgentDock Coding Prompt

## Agent
Name: ${agent.name}
Type: ${agent.type ?? "Custom"}
Provider: ${agent.provider ?? "Other"}
Status: ${agent.status ?? "Active"}
Notes: ${agent.notes || "No notes provided."}

${projectContext(project)}

${memoriesMarkdown(allowedMemories)}

${skillsMarkdown(allowedSkills)}

${secretsMarkdown(allowedSecrets)}

## Task
${task}

## Expected Work
- Inspect the relevant files first.
- Make focused changes.
- Preserve existing behavior.
- Do not expose raw secret values.
- Report changed files and test commands.
`;
}

export function generateHandoff({
  agent,
  memories,
  project,
  secrets,
  sessions,
  skills,
  target
}: {
  agent: Agent;
  memories: Memory[];
  project: Project;
  secrets: Secret[];
  sessions: PromptSession[];
  skills: Skill[];
  target: HandoffTarget;
}) {
  const allowedMemories = getAgentMemories(agent, memories);
  const allowedSkills = getAgentSkills(agent, skills);
  const allowedSecrets = getAgentSecrets(agent, secrets);

  return `# AgentDock Handoff Package

## Source Agent
Name: ${agent.name}
Type: ${agent.type ?? "Custom"}
Provider: ${agent.provider ?? "Other"}
Status: ${agent.status ?? "Active"}

## Export Target
${target}

${projectContext(project)}

${memoriesMarkdown(allowedMemories)}

${skillsMarkdown(allowedSkills)}

${secretsMarkdown(allowedSecrets)}

## Recent Sessions
${sessions.length > 0 ? sessions.slice(0, 5).map((session) => `### ${session.title}\nType: ${session.type ?? "Prompt"}\nStatus: ${session.status ?? "Draft"}\nTask: ${session.task ?? ""}`).join("\n\n") : "No recent sessions."}

## Transfer Instructions
- Continue using this AgentDock context.
- Preserve working behavior.
- Do not expose raw secrets.
- Provide files changed and validation steps.
`;
}

function getAgentMemories(agent: Agent, memories: Memory[]) {
  if (agent.memory_access === "No memory access") return [];
  if (agent.memory_access === "Selected memories") {
    const selectedIds = new Set(agent.selected_memory_ids ?? []);
    return memories.filter((memory) => selectedIds.has(memory.id));
  }
  return memories;
}

function getAgentSkills(agent: Agent, skills: Skill[]) {
  if (agent.skills_access === "No skills access") return [];
  if (agent.skills_access === "Selected skills") {
    const selectedIds = new Set(agent.selected_skill_ids ?? []);
    return skills.filter((skill) => selectedIds.has(skill.id));
  }
  return skills;
}

function getAgentSecrets(agent: Agent, secrets: Secret[]) {
  if (agent.secrets_access === "No secrets access") return [];
  const selectedIds = new Set(agent.selected_secret_ids ?? []);
  return secrets.filter((secret) => selectedIds.has(secret.id));
}
